let User,CustomErrorHandler;_812‍.x([["default",()=>_812‍.o]]);_812‍.w("../../models",[["User",["User"],function(v){User=v}]]);_812‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
    async me(req, res, next) {
        try {
            const user = await User.findOne({ _id: req.user._id }).select('-password -updatedAt -__v');
            if (!user) {
                return next(CustomErrorHandler.notFound());
            }
            res.json(user);
        } catch(err) {
           return next(err);
        }
    }
};

_812‍.d(userController);